from pathlib import Path
ROOT = Path(__file__).parent
RESULTS_DIR = ROOT / 'results'
RESULTS_DIR.mkdir(exist_ok=True)
DATA_ROOTS = {'CHB_MIT': Path('data/raw/chb-mit'), 'TUH': Path('data/raw/tuh_eeg_seizure'), 'SIENA': Path('data/raw/siena'), 'SPARCNET': Path('data/raw/sparcnet'), 'ICARE': Path('data/raw/i-care'), 'ECAMS': Path('data/raw/e-cam-s'), 'SAH_PROS': Path('data/raw/sah_prospective'), 'SAH_AUTO': Path('data/raw/sah_automated')}
SPARCNET_FEATURES_CSV = DATA_ROOTS['SPARCNET'] / 'sparcnet_features.csv'
ECAMS_LABELS_CSV = DATA_ROOTS['ECAMS'] / 'E_CAM_S_Data.csv'
SAH_MASTER_XLSX = DATA_ROOTS['SAH_PROS'] / 'sah_data_MASTER_FOR_ANALYSIS_v5.xlsx'
STANDARD_CHANNELS = ['Fp1', 'Fp2', 'F3', 'F4', 'F7', 'F8', 'Fz', 'C3', 'C4', 'Cz', 'T3', 'T4', 'T5', 'T6', 'P3', 'P4', 'Pz', 'O1', 'O2']
N_CHANNELS = len(STANDARD_CHANNELS)
TARGET_SFREQ = 256
BANDPASS_LOW = 0.5
BANDPASS_HIGH = 45.0
BANDPASS_ORDER = 4
NOTCH_FREQS = [50.0, 60.0]
AMP_THRESHOLD_UV = 500.0
FLATLINE_THRESH_S = 5.0
ZSCORE_WINDOW_S = 60.0
WINDOW_S = 10
OVERLAP_S = 5
SEQ_LEN = 36
ENTROPY_HISTORY_S = 15 * 60
INSTAB_HISTORY_S = 30 * 60
BANDS = {'delta': (1.0, 4.0), 'theta': (4.0, 8.0), 'alpha': (8.0, 13.0), 'beta': (13.0, 30.0), 'gamma': (30.0, 45.0)}
COHERENCE_PAIRS = [('F3', 'P3'), ('F4', 'P4'), ('F3', 'F4'), ('P3', 'P4'), ('Fz', 'Pz')]
PE_ORDER = 5
PE_DELAY = 1
SE_M = 2
SE_R = 0.2
DFA_MIN_WIN = 10
DFA_MAX_WIN = int(WINDOW_S * TARGET_SFREQ // 2)
NETWORK_THRESHOLD = 0.2
LEFT_CHANNELS = ['Fp1', 'F3', 'F7', 'C3', 'T3', 'P3', 'T5', 'O1']
RIGHT_CHANNELS = ['Fp2', 'F4', 'F8', 'C4', 'T4', 'P4', 'T6', 'O2']
PATTERN1_FEATURES = ['alpha_coh_FpO', 'alpha_coh_FO', 'alpha_coh_IH', 'global_efficiency', 'modularity', 'posterior_clustering', 'frontal_clustering']
PATTERN2_FEATURES = ['alpha_coh_FC_aff', 'alpha_coh_CP_aff', 'alpha_coh_PO_aff', 'coherence_asymmetry', 'hemispheric_density']
PATTERN3_FEATURES = ['alpha_coh_FC', 'alpha_coh_CP', 'alpha_coh_FP', 'frontal_theta_ratio', 'frontal_centrality', 'network_variance']
GLOBAL_FEATURES = ['spectral_slope', 'broadband_power', 'full_entropy', 'overall_instability']
D_PROJ = 64
D_HIDDEN = 128
N_LAYERS = 2
DROPOUT = 0.3
BRANCH_DROPOUT = 0.2
LEARNING_RATE = 0.001
LR_MIN = 1e-06
WEIGHT_DECAY = 0.0001
BATCH_SIZE = 32
MAX_EPOCHS = 100
PATIENCE = 10
GRAD_CLIP = 1.0
AUX_LAMBDA = 0.3
NUM_CLASSES = 3
VALIDATION_FRAC = 0.15
BFI_PRE_WEIGHT = 0.5
BFI_IMM_WEIGHT = 1.0
BFI_ALARM_THRESHOLD = 70
ALARM_SUSTAINED_S = 120
BOOTSTRAP_ITERS = 1000
ECE_BINS = 10
FDR_ALPHA = 0.01
SHAM_REPEATS = 10
OPTUNA_TRIALS = 50
OPTUNA_TIMEOUT = 3600
RANDOM_SEED = 42
NUM_WORKERS = 4